### ISSUE TITLE
Duplicate Burnham with invisible character

### ISSUE THREAD

**Issue by xangregg** [BirkoRuzicka/Star-Trek-Transcripts#2]
In Episode DIS006 there are both (as displayed in BBEdit):
> "\ufeffBURNHAM": ["Personal Log, Specialist Michael Burnham. ...

and
> "BURNHAM": ["Starships have power-redundant relays....

\ufeff is a byte-order mark, which is usually only at the beginning of a file.

Now that I look for it, it occurs in one other place:

> "\ufeffSARU": ["We all come from somewhere. ...

**Comment by BirkoRuzicka** [comment]
This issue has been addressed and fixed in the cleaner version of the dataset I just uploaded.
